### ISSUE TITLE
Updates to chronological history

### ISSUE THREAD

**Issue by gvwilson** [carpentries/the-carpentries-lessons-learned#4]
- Sections 2.1-2.2 on prehistory should be collapsed into one and shortened.
- Sections 2.5 ("Version 6: A True Community Project") and 2.6 ("Data Carpentry") should be replaced with sections summarizing events since 2015.

**Comment by lexnederbragt** [comment]
I wouldn't mind adding a paragraph/subsection about finding the right governance model, summarising the upcoming blog post about Carpentries Governance: https://carpentries.org/blog/2021/07/carpentries-governance.

**Comment by jduckles** [comment]
A first stab at simplifying the timeline added as a `.tex` file (assuming thats what we'll use in the end). I'm probably missing a few things, and some stats need to be added.
